/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Category, categorySchema } from './category';
import { StatusEnum, statusEnumSchema } from './statusEnum';
import { Tag, tagSchema } from './tag';

export interface Pet {
  id?: bigint;
  category?: Category;
  name: string;
  photoUrls: string[];
  tags?: Tag[];
  /** pet status in the store */
  status?: StatusEnum;
}

export const petSchema: Schema<Pet> = object({
  id: ['id', optional(bigint())],
  category: ['category', optional(lazy(() => categorySchema))],
  name: ['name', string()],
  photoUrls: ['photoUrls', array(string(), { xmlItemName: 'photoUrl' })],
  tags: [
    'tags',
    optional(array(lazy(() => tagSchema), { xmlItemName: 'Tag' })),
  ],
  status: ['status', optional(statusEnumSchema)],
});
