/**
 * Swagger PetstoreLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuthenticatorInterface, passThroughInterceptor } from './core';
export const customAuthenticationProvider = ({
  password,
}: {
  password: string;
}): AuthenticatorInterface<boolean> => {
  return (requiresAuth?: boolean) => {
    if (!requiresAuth) {
      return passThroughInterceptor;
    }
       return (request, options, next) => {
      return next(request, options);
    };
  };
};
